# -*- coding: utf-8 -*-
"""ONMT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ljQBkm9DFKWLuGLxCY1VtbBL-hV9LS25
"""

# Force uninstall any existing PyTorch, torchaudio, and torchvision
!pip uninstall -y torch torchaudio torchvision

# Install the latest compatible versions
!pip install torch==2.5.1+cu121 torchvision==0.20.1+cu121 torchaudio==2.5.1+cu121 --index-url https://download.pytorch.org/whl/cu121

# Confirm PyTorch installation
!python -c "import torch; print(torch.__version__)"

# Install OpenNMT and its dependencies
!pip install OpenNMT-py==1.2.0

# Verify installation of OpenNMT
!which onmt_preprocess
!which onmt_train
!which onmt_translate

# Confirm OpenNMT version is available
!onmt_preprocess --version

# Confirm OpenNMT installation
!which onmt_preprocess
!which onmt_train
!which onmt_translate

# Clear any previous data
!rm -rf data/*
!rm -rf dataset.zip

# Download Multi30K dataset
!wget https://github.com/multi30k/dataset/archive/refs/heads/master.zip -O dataset.zip
!unzip dataset.zip -d data/

# Map tokenized train/validation data to expected names
!cp data/dataset-master/data/task1/tok/train.lc.norm.tok.en data/src-train.txt
!cp data/dataset-master/data/task1/tok/train.lc.norm.tok.de data/tgt-train.txt
!cp data/dataset-master/data/task1/tok/val.lc.norm.tok.en data/src-val.txt
!cp data/dataset-master/data/task1/tok/val.lc.norm.tok.de data/tgt-val.txt

# Debug the tokenized data existence
!ls -l data/
!cat data/src-train.txt
!cat data/tgt-train.txt

# Run preprocessing
!onmt_preprocess --train_src data/src-train.txt --train_tgt data/tgt-train.txt \
    --valid_src data/src-val.txt --valid_tgt data/tgt-val.txt \
    --save_data /content/demo --overwrite

# Verify preprocessed output
!ls -l data/demo/

# Train the model without GPU if necessary
!onmt_train --data data/demo --save_model model --train_steps 1000